theme: minima
title: Mr. Market
Description: Mr. Market mission is to fight against financial literacy and connect financial audience into one single platform where people can ask, discuss and collect feedback and cover all financial assets topics in one spot wheatear it’s stocks, cryptocurrencies, bonds, ETFs, or gold. 
